# Generated by Django 5.0.4 on 2024-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='bill_date',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
