# Generated by Django 5.0.4 on 2024-08-12 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0005_alter_bill_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
