# Generated by Django 5.0.4 on 2024-08-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0007_alter_bill_bill_number_alter_bill_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_number',
            field=models.CharField(default='DEFAULT_VALUE', max_length=10),
        ),
    ]
