# Generated by Django 5.0.4 on 2024-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0008_bill_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
