# Generated by Django 5.0.4 on 2024-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0009_alter_bill_customer_name_alter_bill_customer_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='bill_date',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='product',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=20),
        ),
    ]
