# Generated by Django 5.0.4 on 2024-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0014_remove_bill_total_amount_remove_bill_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Pending', 'Pending'), ('Delay', 'Delay')], default='Cash', max_length=50),
        ),
    ]
