# Generated by Django 5.0.4 on 2024-08-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0016_bill_customer_address_alter_bill_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer_address',
        ),
    ]
