# Generated by Django 5.0.4 on 2024-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0017_remove_bill_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
            ],
        ),
    ]
