# Generated by Django 5.0.4 on 2024-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0018_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
