# Generated by Django 5.0.4 on 2024-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0022_alter_customer_date_of_birth_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.CharField(default='Default Address', max_length=1000),
        ),
    ]
