# Generated by Django 5.0.4 on 2024-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0026_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Default Bio', max_length=5000),
        ),
    ]
