# Generated by Django 5.0.4 on 2024-08-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0027_userprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='user_number',
        ),
    ]
