# Generated by Django 5.0.4 on 2024-08-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_System_App', '0028_rename_phone_number_userprofile_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
